# Part 1: Linear Algebra

## Introduction
In this section of the assignment, we will demonstrate the capabilities of Python to execute a number of linear-algebraic tasks, and describe which libraries we must use to replicate MATLAB's functionality as explained in the assignment.

## Import libraries
To work with vectors, we will need to take advantage of Python's `numpy` library, which will allow us to define vectors and many of their operations.

In [1]:
import numpy as np

## Problems

### 1) Vectors
Here, we are given a number of vectors to define, and then we are told to multiply them in a few combinations. Let's use `numpy` to define the given vectors:

In [2]:
a = np.array([0, 0, 1])
b = np.array([1, 1, 0])
c = np.array([0, -1, -1])

Note that we are technically defining these as row vectors &mdash; unlike MATLAB, `numpy` has no inherent distinction between row and column vectors if said vectors are explicitly one-dimensional.

Now, let's calculate the scalar products that we're told to calculate. Here, we will use the `numpy.dot()` function:

In [3]:
products = [np.dot(a, b), np.dot(b, a), 
            np.dot(a, c), np.dot(b, c)]

# These products are, by default, numpy's own int64 type, 
# so we're going to convert them to Python's built-in int type
print([int(p) for p in products])

[0, 0, -1, -1]


Why do these results make sense geometrically? Well, let's take a closer look at the actual vectors involved in the multiplication operations.  

$\mathbf{a}\cdot\mathbf{b}=0$  
Looking at the components of $\mathbf{a}$ and $\mathbf{b}$, the two vectors are *complementary*, meaning each non-zero component of one vector is in the same position as a zero component in the other vector. In linear algebra, this makes the two vectors *orthogonal*, or perpendicular, meaning their dot product is definitionally equal to $0$.  

$\mathbf{b}\cdot\mathbf{a}=0$  
Another definitional aspect of the dot product is its *commutativity*; that is, the order of two dot-multiplied vectors does not matter. Thus, $\mathbf{b}\cdot\mathbf{a}$ is equal to $\mathbf{a}\cdot\mathbf{b}$, and both are $0$.  

$\mathbf{a}\cdot\mathbf{c}=-1$ and $\mathbf{b}\cdot\mathbf{c}=-1$  
These are both equal to $-1$, which makes sense as neither $\mathbf{a}$ nor $\mathbf{b}$ are orthogonal to $\mathbf{c}$. In addition, since the sign is negative, this means that the angles between $\mathbf{a}$ and $\mathbf{c}$ as well as between $\mathbf{b}$ and $\mathbf{c}$ are greater than $90^{\circ}$, or obtuse. The angles are also certainly less than $180^{\circ}$, which would mean the vectors point in opposite directions, as if the angles were $180^{\circ}$, the vectors' dot product would be equal to the negative product of the respective two vectors' magnitudes.

### 2) Matrices
Now, we're moving onto matrices, which we can similarly use `numpy`'s array feature for:

In [4]:
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [-1, 0, 1]])
B = np.array([[1, 0, 0],
              [0, 1, 0],
              [1, 0, 1]])
C = np.array([[0, -1, 0],
              [1, 0, 0],
              [0, 0, 0]])

We're now asked to multiply these matrices in a few given orders. Let's continue to use `numpy` to calculate these products, specifically the `numpy.matmul()` function:

In [5]:
# These three are pretty straightforward
AB = np.matmul(A, B)
BC = np.matmul(B, C)
CB = np.matmul(C, B)

# Now, one of our matrices is transposed
# We can use numpy's transpose shorthand for this calculation
BC_T = np.matmul(B, C.T)

# Now, let's print our matrices
print(str(AB) + "\n" + str(BC) + "\n"
      + str(CB) + "\n" + str(BC_T))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 0 -1  0]
 [ 1  0  0]
 [ 0 -1  0]]
[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  0]]
[[ 0  1  0]
 [-1  0  0]
 [ 0  1  0]]


Our results are as follows:  
  
$\mathbf{AB}=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}\;\;$  
$\mathbf{BC}=\begin{bmatrix} 0 & -1 & 0 \\ 1 & 0 & 0 \\ 0 & -1 & 0 \end{bmatrix}\;\;$  
$\mathbf{CB}=\begin{bmatrix} 0 & -1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}\;\;$  
$\mathbf{BC^T}=\begin{bmatrix} 0 & 1 & 0 \\ -1 & 0 & 0 \\ 0 & 1 & 0 \end{bmatrix}\;\;$
  
We can also find the inverse of $\mathbf{A}$ as follows:

In [6]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]


Our result is as follows:  
  
$\mathbf{A^{-1}}=\begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 1 & 0 & 1\end{bmatrix}$

Next, to explore the linear operation that is defined by $\mathbf{C}$, let's multiply it by a few arbitrary vectors in $\mathbb{R}^3$ and examine the results.

In [7]:
# Define arbitrary vectors
vect_1 = np.array([1, 1, 1])
vect_2 = np.array([10, 5, 10])
vect_3 = np.array([2, 3, 1])

# Multiply each vector
products = [np.matmul(C, vect_1), np.matmul(C, vect_2), np.matmul(C, vect_3)]
print(products)

[array([-1,  1,  0]), array([-5, 10,  0]), array([-3,  2,  0])]


The results are as follows:  
  
$\mathbf{Cv_{1}}=\begin{bmatrix}-1 \\ 1 \\ 0\end{bmatrix}\;\;$ 
$\mathbf{Cv_{2}}=\begin{bmatrix}-5 \\ 10 \\ 0\end{bmatrix}\;\;$ 
$\mathbf{Cv_{3}}=\begin{bmatrix}-3 \\ 2 \\ 0\end{bmatrix}$  
  
The resulting linear operation is pretty clear: the $z$-component of the vector is set to $0$, projecting the vector onto the $xy$-plane; the $x$- and $y$-components are then swapped, and the new $x$-component is negated, which both serve to rotate the projected vector $90^{\circ}$ counterclockwise. The resultant vector will thus be an $xy$-projected version of the original vector rotated $90^{\circ}$ from the original, and always orthogonal.  
We know that $\mathbf{C}$ is **not invertible**, as the matrix is neither full row- or column-rank (the last row and column are both the zero vector), and invertible matrices are always both full row-rank and column-rank.

Now, we're asked which of $\mathbf{a}$, $\mathbf{b}$, or $\mathbf{c}$ are eigenvectors of $\mathbf{B}$. If a vector is an eigenvector of a matrix, the product of the matrix and vector will simply scale said vector. As such, let's test each of the three matrix products:

In [8]:
products = [np.matmul(B, a), np.matmul(B, b), np.matmul(B, c)]

# Print products next to original vectors
for [original, product] in zip([a, b, c], products):
    print(str(original) + str(product) + "\n")

[0 0 1][0 0 1]

[1 1 0][1 1 1]

[ 0 -1 -1][ 0 -1 -1]



The results are as follows:  
  
$\mathbf{Ba} = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}\;\;$
$\mathbf{Bb} = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}\;\;$
$\mathbf{Bc} = \begin{bmatrix} 0 \\ -1 \\ -1 \end{bmatrix}\;\;$  
  
We can see that $\mathbf{Ba}$ and $\mathbf{Bc}$ not only scaled the original two vectors, but actually preserved them entirely, meaning they were scaled by a factor of $1$. This means that $\mathbf{a}$ and $\mathbf{c}$ are eigenvectors of $\mathbf{B}$, both with eigenvalues of $\lambda = 1$.